### ISSUE TITLE
How to use RTKLIB and Eagle Eye for Localization

### ISSUE THREAD

**Issue by joewong00** [MapIV/eagleye#256]
Hi,

After reading through the documentations, I'm still a little vague about the whole idea of using eagle eye for localization, so here are my questions:

1. Is the input from RTKLIB necessary? I realised that the rosbag contains the topic "/rtklib_nav", which is from RTKLIB ros bridge. It seems like this input is required to run eagle eye rt based on the config file.

2. In RTKLIB configurations, I noticed that a base station input is required. However, I do not have that so does that mean that I cannot use RTKLIB to output the rtklib_nav topics?

3. Currently, I only have the IMU topic as well as a fix type GPS data. I assume that I can use the eagle eye rt with the canless mode, but if I have the wheel odometry data, I can use the CAN mode by just using the odometry twist data right?

These are my questions and I hope that you can assist me here. I am hoping to perform localization of my robot with the use of GPS data along with the IMU for a more precise pose in the map. 

Thank you.

**Comment by rsasaki0109** [comment]
1
Input from RTKLIB is not required. GNSS-related input can be selected from the following options.
https://github.com/MapIV/eagleye/blob/main-ros1/eagleye_rt/config/eagleye_config.yaml#L11-L15

2
You can use RTKLIB to output rtklib_nav topics without needing base station input, but in that case this package is lane-level accurate.
Base station input is required if you want to get more accurate poses with cm accuracy on the map.

3
If wheel odometry data is available, CAN mode can be used. Note, however, that the kinematic model assumes a car and does not support actuated two-wheeled or omnidirectional robots.

**Comment by joewong00** [comment]
Hi, thanks for the reply. 

Regarding the first question, if I do not have any input from RTKLIB, what should I put in the GNSS velocity source? I tried using the odometry twist data, but when I tried running, the "Eagleye status" shows that the latitude and longitude under rtklib (input) shows a zero value. 

About your second reply, may I know how can I obtain the rtklib_nav topics without the input from base station? I'm a little confused with the configurations in RTKLIB.

Thank you.

**Comment by rsasaki0109** [comment]
1
The GNSS input options for latitude/longitude and velocity information include the following
```
gnss:
  velocity_source_type: 0 # rtklib_msgs/RtklibNav: 0, nmea_msgs/Sentence: 1, ublox_msgs/NavPVT: 2, geometry_msgs/TwistWithCovarianceStamped: 3
  velocity_source_topic:  /rtklib_nav
  llh_source_type: 0 # rtklib_msgs/RtklibNav: 0, nmea_msgs/Sentence: 1, sensor_msgs/NavSatFix: 2
  llh_source_topic:  /rtklib_nav
```

2

For more information, please see the RTKLIB documentation and how to use it, but the following is a good reference for setting up without a base station.
The key point is to set `pos1-posmode` to `single`.

https://github.com/MapIV/RTKLIB/blob/rtklib_ros_bridge_b34/app/consapp/rtkrcv/conf/rtklib_ros_bridge_single.conf
