### ISSUE TITLE
F9P settings

### ISSUE THREAD

**Issue by minglok943** [MapIV/eagleye#323]
First, thanks for the brilliant packages. 

My zed-f9p firmware version is 1.32 and I don't want to change the firmware version.
![image](https://github.com/MapIV/eagleye/assets/80484903/9e92d8c1-be76-4ea2-9392-c99c43ab3cc9)
I am using three ardusimple rtk2b board, one at base station, two on robot. 

(1) Settings for receivers that output aircraft that output NMEA (positioning results RTK'd by the F9P internal engine)
eagleye_f9p_nmea_conf.txt
https://www.dropbox.com/s/3viqyqutipn5dpj/eagleye_f9p_nmea_conf.txt?dl=0
(2) Settings for receivers that measure RAW data through RTKLIB and output Doppler velocity.
eagleye_f9p_raw_conf.txt
https://www.dropbox.com/s/acz98v30rtgbmsx/eagleye_f9p_raw_conf.txt?dl=0

Regarding above, can I understand that the first zed-f9p on robot should output NMEA only like image below
![image](https://github.com/MapIV/eagleye/assets/80484903/84b44093-a608-459e-a5ed-4caa4196bb99)

while the second zed-f9p on robot should output Raw message only like the image below only?
![image](https://github.com/MapIV/eagleye/assets/80484903/f25110e1-a4c6-4481-a2cd-94aa854a116d)

Or other settings need to be configured?

**Comment by rsasaki0109** [comment]
These settings should be fine. Through the ROS node, you should check the /nmea_sentence or /fix topic from (1), and the /rtklib_nav topic from (2) as they will be outputted accordingly.

**Comment by minglok943** [comment]
From (1), when I run roslaunch f9p_nmea_sentence.launch, warning [ WARN] [1711257286.189094931]: Null byte received from serial port, flushing buffer was shown. 
![image](https://github.com/MapIV/eagleye/assets/80484903/68e40db8-525a-479b-ab69-602660b0d36c)

however, the topic /f9p/nmea_sentence was still publishing 
![image](https://github.com/MapIV/eagleye/assets/80484903/20472bdd-e898-43d0-af02-aece1fe26d84)

Is this normal? 

Also, our final goal is to get robot's heading in dual antenna mode,

if run eagleeye_rt.launch in multi_antenna_mode, we need to set the config.yaml accordingly,
``` 
gnss:
  velocity_source_type: 0 # rtklib_msgs/RtklibNav: 0, nmea_msgs/Sentence: 1, ublox_msgs/NavPVT: 2, geometry_msgs/TwistWithCovarianceStamped: 3
  velocity_source_topic:  /rtklib_nav
  llh_source_type: 1 # rtklib_msgs/RtklibNav: 0, nmea_msgs/Sentence: 1, sensor_msgs/NavSatFix: 2
  llh_source_topic: /main/mosaic/nmea_sentence
sub_gnss:
  llh_source_type: 1 # nmea_msgs/Sentence: 1, sensor_msgs/NavSatFix: 2
  llh_source_topic: /sub/mosaic/nmea_sentence
```

[KumarRobotics/ublox](https://github.com/KumarRobotics/ublox.git)
this package publishes 
~fix([sensor_msgs/NavSatFix](http://docs.ros.org/api/sensor_msgs/html/msg/NavSatFix.html))

Navigation Satellite fix.

~fix_velocity([geometry_msgs/TwistWithCovarianceStamped](http://docs.ros.org/jade/api/geometry_msgs/html/msg/TwistWithCovarianceStamped.html))

Velocity in local ENU frame.

for gnss and subgnss, can I use that as source?

**Comment by rsasaki0109** [comment]
> Is this normal?

If the topic is being published, then there's no problem.

> can I use that as source?

The fix is fine, but since the fix_velocity is in the ENU system, it needs to be converted to the ECEF system.

**Comment by minglok943** [comment]
I connected 2 simplertk2b to a laptop,
First SimpleRtk2B(gnss)
![image](https://github.com/MapIV/eagleye/assets/80484903/91b92c13-eda2-40d7-9163-c8fe03276745)
For /dev/ttyACM0, I got the /rtklib/nav by the rtkrcv and rtklib bridge,
For /dev/ttyUSB0, I got the /f9p/nmea_sentence by nmea_comms

Second SimpleRtk2B(subgnss), /dev/ttyACM1
I want to get the nmea sentence with the same way but I got 
[ERROR] [1711332945.879142881]: Unable to bind socket. Is port 29500 in use? Retrying every 1s.

How to run two instances of nmea_comms ?

Therefore, I tried also using the ublox package to get the llh for subgnss.
[Recorded rosbag file](https://drive.google.com/file/d/1aVnrK-Oi3-hZoiHbwIdFV4OZk7D4xA27/view?usp=sharing)

And I set the config as below
```
gnss:
  velocity_source_type: 0 # rtklib_msgs/RtklibNav: 0, nmea_msgs/Sentence: 1, ublox_msgs/NavPVT: 2, geometry_msgs/TwistWithCovarianceStamped: 3
  velocity_source_topic:  /rtklib_nav
  llh_source_type: 1 # rtklib_msgs/RtklibNav: 0, nmea_msgs/Sentence: 1, sensor_msgs/NavSatFix: 2
  llh_source_topic: /f9p/nmea_sentence
sub_gnss:
  llh_source_type: 2 # nmea_msgs/Sentence: 1, sensor_msgs/NavSatFix: 2
  llh_source_topic: /ublox2/fix
```

then I run roslaunch eagleye_gnss_converter gnss_converter.launch use_multi_antenna_mode:=true, but I got the error and the /sub_navsat/gga  is not publishing also, how can I troubleshoot this?
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
[navsat/gnss_converter_node-1] process has died [pid 67476, exit code -6, cmd /home/a2tech/catkin_ws/devel/lib/eagleye_gnss_converter/gnss_converter_node __name:=gnss_converter_node __log:=/home/a2tech/.ros/log/45692a18-ea5c-11ee-bed6-fb2b8dd8ccff/navsat-gnss_converter_node-1.log].
log file: /home/a2tech/.ros/log/45692a18-ea5c-11ee-bed6-fb2b8dd8ccff/navsat-gnss_converter_node-1*.log
```

**Comment by rsasaki0109** [comment]
Please specify using what is displayed by the 'ls /dev/serial/by-id/*' command, instead of /dev/ttyACMX.

> I got the error and the /sub_navsat/gga is not publishing also, how can I troubleshoot this?

I will check on this later.

**Comment by rsasaki0109** [comment]
Does the gnss_converter die on startup, or does it die when subscribing to a topic?

Can you launch gnss_converter.xml without any issues within eagleye_rt.launch.xml?
https://github.com/MapIV/eagleye/blob/autoware-main/eagleye_rt/launch/eagleye_rt.launch.xml#L135

**Comment by minglok943** [comment]
```
  // Callback functions
void nmea_callback(const nmea_msgs::Sentence::ConstPtr &msg)
{
  nmea_msgs::Gpgga gga;
  nmea_msgs::Gprmc rmc;
  sensor_msgs::NavSatFix fix;

  sentence.header = msg->header;
  sentence.sentence = msg->sentence;
  nmea2fix_converter(sentence, &fix, &gga, &rmc);
  if (fix.header.stamp.toSec() != 0)
  {
    gga.header.frame_id = fix.header.frame_id = "gnss";
    pub1.publish(fix);
    pub2.publish(gga);
  }
  if (rmc.header.stamp.toSec() != 0)
  {
    rmc.header.frame_id = "gnss";
    pub3.publish(rmc);
  }
}
```
I found out that the gga message needed by gnss_compass is only published when we use nmea message. I also tried the rosbag provided 
[GNSS: Ublox F9P with RTK IMU: Tamagawa AU7684 LiDAR: Velodyne VLP-32C](https://www.dropbox.com/s/w9ag6gs17bi80st/eagleye_sample_20200715.bag?dl=0)
![image](https://github.com/MapIV/eagleye/assets/80484903/1c1972e5-286c-4659-bedb-0a36f48bcb0d)

![image](https://github.com/MapIV/eagleye/assets/80484903/d52131e9-c2fb-4716-939c-ed436af06068)

I assumed the rtklib_nav and /f9p/fix in the rosbag are from the first gnss, and the /fix is from the second gnss, 
then I run eagleeye_rt.launch in dual antenna mode and I found out that the gnss_compass node is not running but the heading estimation works fine. The gnss_converter node is publishing /eagleye/navsat/rtklib_nav for heading estimation nodes. 

So can I conclude that as long as I got the gnss_converter node publishing /eagleeye/navsat/rtklib_nav, I can procede to the next stage?

The package [KumarRobotics/ublox](https://github.com/KumarRobotics/ublox.git) I mentioned previously also support publishing of NavPvt message, any modification needed for the message before I forward the message to gnss_converter node?
```
gnss:
  velocity_source_type: 2 # rtklib_msgs/RtklibNav: 0, nmea_msgs/Sentence: 1, ublox_msgs/NavPVT: 2, geometry_msgs/TwistWithCovarianceStamped: 3
  velocity_source_topic:  /ublox1/navpvt
  llh_source_type: 2 # rtklib_msgs/RtklibNav: 0, nmea_msgs/Sentence: 1, sensor_msgs/NavSatFix: 2
  llh_source_topic: /ublox1/fix
sub_gnss:
  llh_source_type: 2 # nmea_msgs/Sentence: 1, sensor_msgs/NavSatFix: 2
  llh_source_topic: /ublox2/fix
  ```
